# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: lazybrew
    main: ./main.go
    binary: lazybrew
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: lazybrew
    builds:
      - lazybrew
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - name: lazybrew
    repository:
      owner: zh1C
      name: homebrew-lazybrew
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/zh1C/lazybrew"
    description: "A lazy TUI for Homebrew"
    license: "MIT"
    install: |
      bin.install "lazybrew"
    test: |
      assert_match version.to_s, shell_output("#{bin}/lazybrew --version", 2)
